def remove_leading_zeros(ip_address):
    
    octets = ip_address.split('.')
    
    cleaned_octets = [str(int(octet)) for octet in octets]
    
    cleaned_ip_address = '.'.join(cleaned_octets)
    
    return cleaned_ip_address

input_ip = "216.08.094.196"
output_ip = remove_leading_zeros(input_ip)
print(f"Original IP: {input_ip}")
print(f"Cleaned IP: {output_ip}")
