def safe_divide(nr, dr):
    try:
        result = nr / dr
    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")
        return None  
    else:
        return result  
    finally:
        print("Division operation attempted.")  

print(safe_divide(10, 2))
print(safe_divide(10, 0))
