class Account:
    def __init__(self, holder_name, account_number, balance=0):
        self.holder_name = holder_name
        self.account_number = account_number
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            return True
        return False

    def withdraw(self, amount):
        if 0 < amount <= self.balance:
            self.balance -= amount
            return True
        return False

    def get_balance(self):
        return self.balance


class Bank:
    def __init__(self):
        self.accounts = {}

    def create_account(self, holder_name, initial_deposit):
        account_number = len(self.accounts) + 1
        new_account = Account(holder_name, account_number, initial_deposit)
        self.accounts[account_number] = new_account
        return account_number

    def get_account(self, account_number):
        return self.accounts.get(account_number, None)

    def deposit(self, account_number, amount):
        account = self.get_account(account_number)
        if account:
            return account.deposit(amount)
        return False

    def withdraw(self, account_number, amount):
        account = self.get_account(account_number)
        if account:
            return account.withdraw(amount)
        return False

    def transfer(self, source_account_number, destination_account_number, amount):
        source_account = self.get_account(source_account_number)
        destination_account = self.get_account(destination_account_number)
        if source_account and destination_account and source_account.withdraw(amount):
            return destination_account.deposit(amount)
        return False

my_bank = Bank()
acc_num1 = my_bank.create_account("John Doe", 500)
acc_num2 = my_bank.create_account("Jane Doe", 300)
print(my_bank.deposit(acc_num1, 200))  # Deposit to John's account
print(my_bank.withdraw(acc_num2, 50))   # Withdraw from Jane's account
print(my_bank.transfer(acc_num1, acc_num2, 100))  # Transfer from John to Jane
print(my_bank.get_account(acc_num1).get_balance())  # Check John's balance
print(my_bank.get_account(acc_num2).get_balance())  # Check Jane's balance
