class Sentence:
    def __init__(self, text):
        self.words = text.split()
        self.index = 0

    def __iter__(self):
        self.index = 0  # Reset the index for new iterations
        return self

    def __next__(self):
        if self.index < len(self.words):
            word = self.words[self.index]
            self.index += 1
            return word
        else:
            raise StopIteration

    def words_generator(self):
        for word in self.words:
            yield word

sentence_obj = Sentence("this is ignite session")
for word in sentence_obj:
     print(word)

print("----")

for word in sentence_obj.words_generator():
     print(word)
